### ISSUE TITLE
Reporters

### ISSUE THREAD

**Issue by vnickolov** [yaymukund/grunt-simple-mocha#42]
Hello, 

What is the full list of supported reporters? 
I currently tried to use XUnit but I got the following: Warning: invalid reporter "XUnit"

Thank you in advance.

**Comment by leotcsun** [comment]
try 'xunit' all lowercased, worked for me.

**Comment by vnickolov** [comment]
Thank you very much! 

I am no longer working on this project but will have it in mind!

Thank you once again!

**Comment by leotcsun** [comment]
no problem! 
I was looking for a solution and google took me here, so I thought I should answer this in case someone else ends up looking at this issue =)

cheers!

**Comment by yaymukund** [comment]
I've clarified the docs to say that we merely pass the options to the mocha constructor. Hopefully, that should help future users. Thank you for the report, and I'm sorry about the confusion.
