### ISSUE TITLE
The `grep` option may cause confusion

### ISSUE THREAD

**Issue by ts-web** [yaymukund/grunt-simple-mocha#44]
For new users of mocha, they might not know what the `grep` option is for. For people familiar with jasmine, they might think that the value `*-test` pertains to the filename suffix, e.g. `thing-test.js`, since Jasmine by default looks for files like `thing.spec.js`. But that is not what `grep` does.

The README should mention that the `grep` option filters the *tests* and only runs those that match the pattern. It does not run those that don't.

Or else, the README needs to include a basic unit test that works with the configuration. Because most likely, the configuration (as is) won't run the tests that new users write.

**Comment by ekkis** [comment]
so if I can declare in my `Gruntfile.js`:

    simplemocha: {
        all: { src: 'test/*-node.js' }
    }

why would I need `grep`?

**Comment by ts-web** [comment]
@ekkis, the `grep` option does not filter files, but rather the tests themselves. It's a Mocha option. See [Mocha's CLI options](https://mochajs.org/#usage):

    -g, --grep <pattern>                    only run tests matching <pattern>

It says "tests", which apparently means the description string of the `describe()` blocks

**Comment by ts-web** [comment]
This repository should really remove the `grep` option from the examples. It will only confuse people and cause their setups to not run any tests! Because who writes `describe()` blocks containing the string `-test` in the test description?

Since the grep will match none of their `describe` blocks, then none of their tests will run. So `grep` should be removed from the examples.

**Comment by ekkis** [comment]
ah.  that explains why I get `0 passing (0ms)`.  LoL.  thanks guys

**Comment by yaymukund** [comment]
You're right— this is pretty confusing! Thank you for opening the issue and I'm sorry for the confusion. I've clarified in the docs that it merely passes the options to `new Mocha`
