### ISSUE TITLE
How to run mocha in verbose mode?

### ISSUE THREAD

**Issue by Muzietto** [yaymukund/grunt-simple-mocha#48]
My simplemocha run is failing with

    Warning: undefined is not a function Use --force to continue.

How can I run in verbose mode, so to know at which line of which file this `undefined` popped up?.

**Comment by eriksape** [comment]
grunt --verbose

**Comment by Muzietto** [comment]
Wow! Sounds I'm not the only one to know where grunt docs are.
What you're basically avoiding to say is that simplemocha ain't capable to set grunt verbose level by itself. And what if I don't want grunt to verbose out all over the place?
OK, then. How do you spell 'new feature'? Lemme find if there's a place where I can ask for it...
